baseURL = "file:///storage/emulated/0/notesData/kAvyam/"
languageCode = "en-us"
title = "काव्ये विश्वासटिप्पण्यः"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_offline_android"
disablePathToLower = true
[params]
  githubEditMePathBase = "https://github.com/vvasuki/kAvyam/edit/master/content/"
  contactLink = "https://github.com/vvasuki/kAvyam/issues/new"
  env = "production"
  disqusShortcode = "vvasuki-site"